"""initial schema

Revision ID: 5f665d7137f5
Revises: 
Create Date: 2026-05-10 16:46:31.835530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f665d7137f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('founder_address', sa.String(length=42), nullable=False),
    sa.Column('vault_address', sa.String(length=42), nullable=False),
    sa.Column('token_address', sa.String(length=42), nullable=False),
    sa.Column('founder_vault_address', sa.String(length=42), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('incubation_start', sa.BigInteger(), nullable=False),
    sa.Column('public_launch_at', sa.BigInteger(), nullable=True),
    sa.Column('mandate', sa.JSON(), nullable=False),
    sa.Column('mandate_uri', sa.String(length=512), nullable=False),
    sa.Column('mandate_hash', sa.String(length=66), nullable=False),
    sa.Column('reputation', sa.Integer(), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('agent_id', name=op.f('pk_agents')),
    sa.UniqueConstraint('founder_vault_address', name=op.f('uq_agents_founder_vault_address')),
    sa.UniqueConstraint('mandate_hash', name=op.f('uq_agents_mandate_hash')),
    sa.UniqueConstraint('token_address', name=op.f('uq_agents_token_address')),
    sa.UniqueConstraint('vault_address', name=op.f('uq_agents_vault_address'))
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_founder_address'), ['founder_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_phase'), ['phase'], unique=False)

    op.create_table('indexer_state',
    sa.Column('chain_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('last_synced_block', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('chain_id', name=op.f('pk_indexer_state'))
    )
    op.create_table('mandate_blobs',
    sa.Column('mandate_hash', sa.String(length=66), nullable=False),
    sa.Column('mandate_json', sa.JSON(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('ipfs_uri', sa.String(length=512), nullable=True),
    sa.Column('pinned_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('mandate_hash', name=op.f('pk_mandate_blobs'))
    )
    op.create_table('decisions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('before_positions', sa.JSON(), nullable=True),
    sa.Column('after_positions', sa.JSON(), nullable=True),
    sa.Column('nav_before', sa.String(), nullable=True),
    sa.Column('nav_after', sa.String(), nullable=True),
    sa.Column('harvested_usdc', sa.String(), nullable=True),
    sa.Column('harvested_from_sources', sa.JSON(), nullable=True),
    sa.Column('distributed_epoch', sa.Integer(), nullable=True),
    sa.Column('distributed_holders_usdc', sa.String(), nullable=True),
    sa.Column('distributed_carry_usdc', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_decisions_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index('ix_decisions_agent_id_timestamp', ['agent_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_decisions_agent_id_type', ['agent_id', 'type'], unique=False)

    op.create_table('dividend_epochs',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('epoch', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('total_amount_usdc', sa.String(), nullable=False),
    sa.Column('holders_share_usdc', sa.String(), nullable=False),
    sa.Column('carry_share_usdc', sa.String(), nullable=False),
    sa.Column('distributed_at', sa.BigInteger(), nullable=False),
    sa.Column('total_shares_at_snapshot', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_dividend_epochs_agent_id_agents')),
    sa.PrimaryKeyConstraint('agent_id', 'epoch', name=op.f('pk_dividend_epochs'))
    )
    op.create_table('founder_vaults',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('shares_held', sa.String(), nullable=False),
    sa.Column('lockup_ends_at', sa.BigInteger(), nullable=False),
    sa.Column('cumulative_withdrawn_bps', sa.Integer(), nullable=False),
    sa.Column('is_subordination_active', sa.Boolean(), nullable=False),
    sa.Column('carry_balance_usdc', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_founder_vaults_agent_id_agents')),
    sa.PrimaryKeyConstraint('agent_id', name=op.f('pk_founder_vaults'))
    )
    op.create_table('holders',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('balance', sa.String(), nullable=False),
    sa.Column('weight_bps', sa.Integer(), nullable=False),
    sa.Column('first_held_at', sa.BigInteger(), nullable=False),
    sa.Column('cumulative_dividends_claimed_usdc', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_holders_agent_id_agents')),
    sa.PrimaryKeyConstraint('agent_id', 'address', name=op.f('pk_holders'))
    )
    with op.batch_alter_table('holders', schema=None) as batch_op:
        batch_op.create_index('ix_holders_address', ['address'], unique=False)

    op.create_table('narrator_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.BigInteger(), nullable=False),
    sa.Column('week_end', sa.BigInteger(), nullable=False),
    sa.Column('generated_at', sa.BigInteger(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('nav_start', sa.String(), nullable=False),
    sa.Column('nav_end', sa.String(), nullable=False),
    sa.Column('return_bps', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_narrator_notes_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_narrator_notes')),
    sa.UniqueConstraint('agent_id', 'week_start', name=op.f('uq_narrator_notes_agent_id'))
    )
    op.create_table('nav_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('nav_usdc', sa.String(), nullable=False),
    sa.Column('nav_per_share_usdc', sa.String(), nullable=False),
    sa.Column('total_shares', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_nav_history_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nav_history'))
    )
    with op.batch_alter_table('nav_history', schema=None) as batch_op:
        batch_op.create_index('ix_nav_history_agent_id_timestamp', ['agent_id', 'timestamp'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('asset_address', sa.String(length=42), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('value_usdc', sa.String(), nullable=False),
    sa.Column('weight_bps', sa.Integer(), nullable=False),
    sa.Column('price_usdc', sa.String(), nullable=True),
    sa.Column('price_updated_at', sa.BigInteger(), nullable=True),
    sa.Column('price_stale', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_positions_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions')),
    sa.UniqueConstraint('agent_id', 'asset_address', name=op.f('uq_positions_agent_id'))
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_agent_id'), ['agent_id'], unique=False)

    op.create_table('redemption_requests',
    sa.Column('request_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('holder_address', sa.String(length=42), nullable=False),
    sa.Column('shares', sa.String(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.BigInteger(), nullable=False),
    sa.Column('unlock_at', sa.BigInteger(), nullable=False),
    sa.Column('estimated_usdc', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('claimed_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_redemption_requests_agent_id_agents')),
    sa.PrimaryKeyConstraint('request_id', name=op.f('pk_redemption_requests'))
    )
    with op.batch_alter_table('redemption_requests', schema=None) as batch_op:
        batch_op.create_index('ix_redemption_requests_agent_id_status', ['agent_id', 'status'], unique=False)
        batch_op.create_index('ix_redemption_requests_holder_address_status', ['holder_address', 'status'], unique=False)
        batch_op.create_index('ix_redemption_requests_unlock_at', ['unlock_at'], unique=False)

    op.create_table('wind_down_states',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.BigInteger(), nullable=False),
    sa.Column('triggered_by', sa.String(length=42), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('positions_remaining', sa.Integer(), nullable=False),
    sa.Column('estimated_settle_at', sa.BigInteger(), nullable=False),
    sa.Column('senior_claimable_usdc', sa.String(), nullable=False),
    sa.Column('junior_claimable_usdc', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_wind_down_states_agent_id_agents')),
    sa.PrimaryKeyConstraint('agent_id', name=op.f('pk_wind_down_states'))
    )
    op.create_table('dividend_claims',
    sa.Column('agent_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('epoch', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('holder_address', sa.String(length=42), nullable=False),
    sa.Column('amount_usdc', sa.String(), nullable=False),
    sa.Column('claimed', sa.Boolean(), nullable=False),
    sa.Column('claimed_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id', 'epoch'], ['dividend_epochs.agent_id', 'dividend_epochs.epoch'], name=op.f('fk_dividend_claims_agent_id_dividend_epochs')),
    sa.PrimaryKeyConstraint('agent_id', 'epoch', 'holder_address', name=op.f('pk_dividend_claims'))
    )
    with op.batch_alter_table('dividend_claims', schema=None) as batch_op:
        batch_op.create_index('ix_dividend_claims_holder_address_claimed', ['holder_address', 'claimed'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dividend_claims', schema=None) as batch_op:
        batch_op.drop_index('ix_dividend_claims_holder_address_claimed')

    op.drop_table('dividend_claims')
    op.drop_table('wind_down_states')
    with op.batch_alter_table('redemption_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_redemption_requests_unlock_at')
        batch_op.drop_index('ix_redemption_requests_holder_address_status')
        batch_op.drop_index('ix_redemption_requests_agent_id_status')

    op.drop_table('redemption_requests')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_agent_id'))

    op.drop_table('positions')
    with op.batch_alter_table('nav_history', schema=None) as batch_op:
        batch_op.drop_index('ix_nav_history_agent_id_timestamp')

    op.drop_table('nav_history')
    op.drop_table('narrator_notes')
    with op.batch_alter_table('holders', schema=None) as batch_op:
        batch_op.drop_index('ix_holders_address')

    op.drop_table('holders')
    op.drop_table('founder_vaults')
    op.drop_table('dividend_epochs')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_decisions_agent_id_type')
        batch_op.drop_index('ix_decisions_agent_id_timestamp')

    op.drop_table('decisions')
    op.drop_table('mandate_blobs')
    op.drop_table('indexer_state')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_phase'))
        batch_op.drop_index(batch_op.f('ix_agents_founder_address'))

    op.drop_table('agents')
    # ### end Alembic commands ###
